Add `opdatasigverify.md` specification
bitcoincashorg/bitcoincash.org pull request #10
Opened 2018-05-14 20:04 UTC by schancel

Add opdatasigverify spec for November.

@fyookball @Mengerian @gandrewstone

2018-05-15 03:27 UTC, zquestz approved these changes

2018-05-15 12:57 UTC, sickpig commented on spec/opdatasigverify.md
> +Miners, full nodes, and clients will implement the OP_DATASIGVERIFY opcode and activate it during the May 2018 hard fork.
what about:

2018-05-15 12:58 UTC, sickpig commented on spec/opdatasigverify.md
> +Please refer to [this github branch](https://github.com/gandrewstone/BitcoinUnlimited/tree/op_datasigverify) for a complete implementation.  Implementation is in src/test/interpreter.cpp/h and unit t
what about:

2018-05-22 21:12 UTC, fyookball commented
The reasoning not to have a separate OP_CHECKDATASIG seems to make sense because there's no practical use case to check the data and then not do anything with the evaluation.  In practice, OP_CHECKSIG is always combined with a verification op_code afaik.

2018-05-26 09:57 UTC, deadalnix requested changes
This spec is quite not in shape it needs to. In addition to the inline comments, The spec is lacking impact of this on sigops count - clearly these ops should count as sigops.

2018-05-26 09:57 UTC, deadalnix commented on spec/opdatasigverify.md
> +This algorithm is the same operation as the Bitcoin Cash message verification RPC call (e.g signmessage/verifymessage).  The signature must therefore be a pubkey-recoverable signature encoded in bitc
Why does the signature must use a pubkey recoverable algorithm ? It doesn't seems like it's bringing anything to the table to bake in that constraint.

2018-05-26 09:57 UTC, deadalnix commented on spec/opdatasigverify.md
> +The algorithm first computes the double-sha256 hash of the byte string "Bitcoin Signed Message:\n" prepended to the supplied *data* (stack top - 2).  It then computes a pubkey from this hash and the
This part is inconsistent with other parts of the spec.

2018-05-26 09:57 UTC, deadalnix commented on spec/opdatasigverify.md
> +  * output script:  `pubkeyhash OP_DATASIGVERIFY`
It does't make sense to bake the pubkey hash algorithm into that opcode.

2018-05-26 09:57 UTC, deadalnix commented on spec/opdatasigverify.md
> +    Opcode (hex): 0xbb
Namely, strict DER encoding.

2018-05-26 16:01 UTC, fyookball commented on spec/opdatasigverify.md
> +    Opcode (hex): 0xbb
is there at least one use-case for OP_DATACHECKSIG standalone?

2018-05-26 16:18 UTC, deadalnix commented on spec/opdatasigverify.md
> +If there are less then 3 items on the stack, the script fails.  If the pubkeyhash field is not 20 bytes, the script fails.  If the *'type and signature'* field is not 66 bytes, the script fails.  If
Namely, strict DER encoding.

2018-05-29 12:29 UTC, gandrewstone commented on spec/opdatasigverify.md
> +This algorithm is the same operation as the Bitcoin Cash message verification RPC call (e.g signmessage/verifymessage).  The signature must therefore be a pubkey-recoverable signature encoded in bitc
So that the input script does not have to include the pubkey...

2018-05-29 12:33 UTC, gandrewstone commented on spec/opdatasigverify.md
> +  * output script:  `pubkeyhash OP_DATASIGVERIFY`
verses using the unhashed pubkey?  The reason I did it this way is that pubkey hash is shorter, it hides the pubkey until use, and it is aligned with how signmessage/verifymessage works meaning that these RPCs can be used to create the spend and redeem scripts.

2018-05-29 12:34 UTC, sickpig commented on spec/opdatasigverify.md
> +Miners, full nodes, and clients will implement the OP_DATASIGVERIFY opcode and activate it during the May 2018 hard fork.
I would also change `hard fork` with `protocol update`

2018-05-30 04:37 UTC, Mengerian commented on spec/opdatasigverify.md
> +This algorithm is the same operation as the Bitcoin Cash message verification RPC call (e.g signmessage/verifymessage).  The signature must therefore be a pubkey-recoverable signature encoded in bitc
Has there been any discussion on the pros and cons of following the signmessage/verifymessage format?

In many ways, it feels like it would be more elegant to keep the implementation closer to OP_CHECKSIG. Just have the inputs be a Public key, data, and bare DER signature (maybe it would also make sense for the signature to include a "sighash type" similar to OP_CHECKSIG). If scripts don't want to reveal the Public Key in the output script, it can supply a hash in a similar manner as P2PKH.

Since it's consensus critical, it's unclear to me whether the signmessage/verifymessage format has completely well-defined behavior, whereas something closer to unmodified OP_CHECKSIG is battle tested.

2018-05-30 05:34 UTC, Mengerian commented on spec/opdatasigverify.md
> +  * spend script: `data sig`
This example seems strange. It doesn't seem to make sense for the ScriptSig to supply both the data and the signature.

2018-05-30 18:38 UTC, gandrewstone commented on spec/opdatasigverify.md
> +* *data*
The data is unknown when the output script is created.  It is provided by the input script and the signature verifies that the oracle produced this data rather than it being invented by the input script author.  The hash_of_data proposal is not applicable here -- the purpose of this opcode is not to make a commitment to known but unrevealed data.  Think stock price or sporting match scores...

2018-05-30 18:41 UTC, gandrewstone commented
@schancel I am happy to make some of the requested changes based on the above discussion, but since you are the PR author I'm not sure whether I should or you want to.  Let me know and if so, how do you want me to make them?

2018-06-05 14:20 UTC, sickpig commented
paging @schancel 

what do you think about @gandrewstone's proposal made here

https://github.com/bitcoincashorg/bitcoincash.org/pull/10#issuecomment-393272723

2018-06-08 04:29 UTC, Mengerian commented on spec/opdatasigverify.md
> +  * spend script: `data sig`
Since OP_DATASIGVERIFY leaves the data on the Stack on completion, if the data is a value of zero, and is signed properly, then OP_DATASIGVERIFY would complete successfully, but the script in this example would fail since it ends with a zero value left on the stack.

Not sure if this is a practical problem, but it seems like a strange edge case.

2018-06-09 02:18 UTC, ClemensLey commented
My two cents: Like @Mengerian I think that the inputs to OP_CHECKDATASIG should work as similar as possible to OP_CHECKSIG. This would mean that the parameters should be a public key, the message to be signed, and a signature. Like other op codes I think that it should pop the parameters from the stack and push the result (a boolean) onto the stack.

I think the op code would be easier to use if there is only a signature on the stack, not signature + sig_type. If we find strong use cases for other signature checking algorithm we could consider adding a signature type as a 4th parameter, but my feeling is that we should be fine with just a standard signature checking procedure.

Also I think it would be better if we could drop the requirement that the signature must be pubkey-recoverable.

All in all, I think that OP_CHECKDATASIG could be a valuable addition to the Bitcoin scripting language. We just need to do a little work to ensure that it is as easy to use as possible.

2018-08-15 17:08 UTC, Mengerian commented
This proposal has been superseded by https://github.com/bitcoincashorg/bitcoincash.org/pull/93

2018-08-15 17:09 UTC, closed without merging

2021-06-20 09:04 UTC, baby636 reviewed
https://medium.com/@g.andrew.stone/bitcoin-scripting-applications-decision-based-spending-8e7b93d7bdb9

2021-06-20 09:04 UTC, baby636 commented on spec/opdatasigverify.md
> +OP_DATASIGVERIFY allows signed data to be imported into a script.  This data can then have many uses, depending on the rest of the script, such as deciding spendability of several possible addresses.
https://medium.com/@g.andrew.stone/bitcoin-scripting-applications-decision-based-spending-8e7b93d7bdb9