Add specification for November 15, 2020 upgrade
bitcoincashorg/bitcoincash.org pull request #509
Opened 2020-08-13 16:02 UTC by Mengerian

2020-08-13 16:08 UTC, Mengerian commented
Work in Progress, still need to add the actual coinbase rule address.

2020-08-13 16:54 UTC, jasonbcox requested changes

2020-08-13 16:54 UTC, jasonbcox commented on spec/2020-11-15-asert.md
> +
lots of superfluous newlines above this point. please remove them

2020-08-13 16:54 UTC, jasonbcox commented on spec/2020-11-15-asert.md
> +```
The whole psuedocode section is messy. There needs to be more whitespace separating the comments and code such that adjacent lines don't break the "line of sight" between neighboring comments. This improves scanning substantially. Also, those comments should ideally be aligned with nearby comments (only some of them are).

2020-08-13 16:54 UTC, jasonbcox commented on spec/2020-11-15-asert.md
> +#### REQ-ASERT-TARGET-COMPUTATION (target computation)
What's up with these section names? Just spell them out in English. Example: `Requirement: Target Computation`

2020-08-13 16:54 UTC, jasonbcox commented on spec/2020-11-15-asert.md
> +(MTP) [3] network upgrade mechanism.
Rather than referring to the MTP definition, this paragraph should reference to top-level upgrade spec, as the MTP definition is already referenced there.

2020-08-13 16:54 UTC, jasonbcox commented on spec/2020-11-15-asert.md
> +Activation parameters for testnet SHALL be the same as for mainnet.
This section isn't necessary, as it's always implied unless otherwise stated.

2020-08-13 16:54 UTC, jasonbcox commented on spec/2020-11-15-asert.md
> +1. Choice of activation method
Does this section add any value? It doesn't seem to pertain to the DAA spec, but rather the upgrade as a whole.

2020-08-13 16:54 UTC, jasonbcox commented on spec/2020-11-15-asert.md
> +   To be completed.
I think this section can be removed, as the implementation was updated to not use signed bit shifts.

2020-08-13 16:54 UTC, jasonbcox commented on spec/2020-11-15-asert.md
> +## Reference implementations
https://reviews.bitcoinabc.org/D7174

2020-08-13 17:43 UTC, fpelliccioni requested changes

2020-08-13 17:43 UTC, fpelliccioni commented on spec/2020-11-15-upgrade.md
> +## Coinbase Rule
I think this rule would have to go in some ABC spec, not BCH in general.

2020-08-14 05:13 UTC, Mengerian commented
Updated based on latest BCHN changes.

@jasonbcox I updates the C++ reference link based on your comment, but left the quirks of the BCHN spec formatting for now. It might make more sense to fix that stuff up later when we are sure the document has stabilized.

I also expect to have to update the coinbase rule portion of the spec soon with more details.

2020-08-14 09:23 UTC, ftrader commented on spec/2020-11-15-upgrade.md
> +* The addition of a new coinbase rule.
Bitcoin Cash Node will not be implementing this rule for the November upgrade as long as I am lead maintainer of BCHN..

If no other implementations are interested in implementing this either, then it certainly does not belong in a Bitcoin Cash specification.

2020-08-14 09:34 UTC, ftrader commented on spec/2020-11-15-upgrade.md
> +## Coinbase Rule
This May, no miners voted in support of IFP, so I do not see any support from other clients for a coinbase rule that takes an 8% chunk out of BCH mining rewards and directs it to some as yet unspecified address.

On principle, I cannot approve anything that is not fully specified when it concerns a new consensus rule.

Also on principle, I think this is suggesting to change Bitcoin Cash monetary policy, altering mining incentives, introducing the possibility of conflicts of interest and corruption in the form of kickbacks etc.

It would be better if ABC introduced a fiscal policy into their node code that pays however many percent they want of rewards mined with their client, to an address of their choice (themselves for what I care). For this they would not need other clients to implement the same rule.

2020-08-14 11:38 UTC, ftrader commented on spec/2020-11-15-asert.md
> +#### REQ-ASERT-TARGET-COMPUTATION (target computation)
Having proper identifiers for requirements helps with referencing them.

2020-08-14 11:43 UTC, fpelliccioni commented on spec/2020-11-15-asert.md
> +#### REQ-ASERT-TARGET-COMPUTATION (target computation)
> Having proper identifiers for requirements helps with referencing them.
> 
> The short form in English is in brackets.

I agree. It is a common practice in specs and standards.

2020-08-14 11:45 UTC, fpelliccioni commented on spec/2020-11-15-upgrade.md
> +* The addition of a new coinbase rule.
Knuth will not implement this rule, also.

2020-08-14 18:00 UTC, jasonbcox requested changes

2020-08-14 21:44 UTC, Greg-Griffith commented on spec/2020-11-15-upgrade.md
> +* The addition of a new coinbase rule.
BU has voted that we will not implement this rule. please remove it from this document. it is an ABC client specification, not a BCH specification.

2020-08-14 21:44 UTC, Greg-Griffith commented on spec/2020-11-15-upgrade.md
> +## Coinbase Rule
this is not a BCH specification detail. please move this to some ABC specific section. BU will not be implementing this new fiscal policy.

2020-08-14 22:28 UTC, gandrewstone commented on spec/2020-11-15-upgrade.md
> +## Coinbase Rule
BUIP143 (https://bitco.in/forum/threads/buip143-passed-refuse-the-coinbase-tax.25512/) mandates that BU depart from this community if this rule is adopted.  We will bring as many people as possible with us to a coin that is not hemorrhaging value and does not tolerate looters.

2020-08-14 22:35 UTC, jasonbcox commented on spec/2020-11-15-upgrade.md
> +## Coinbase Rule
Bitcoin ABC is the reference implementation for Bitcoin Cash, so the spec belongs here. Not implementing it for your software is your choice.

2020-08-14 22:58 UTC, schancel requested changes

2020-08-14 22:58 UTC, schancel commented on spec/2020-11-15-asert.md
> +#### REQ-ASERT-TARGET-COMPUTATION (target computation)
Recommend splitting this into a different document like in past specs.

2020-08-14 22:58 UTC, schancel commented on spec/2020-11-15-asert.md
> +ALGORITHM aserti3-2d is
Can we just get the C++ implementation?

2020-08-14 22:58 UTC, schancel commented on spec/2020-11-15-asert.md
> +#### REQ-ASERT-TESTNET-DIFF-RESET (testnet difficulty reset)
What's with these titles? Can we use plain English like normal?

2020-08-14 22:58 UTC, schancel commented on spec/2020-11-15-asert.md
> +author: freetrader, Jonathan Toomim, Calin Culianu, Mark Lundeberg
I assume this is MIT licensed?

2020-08-14 23:05 UTC, schancel commented on spec/2020-11-15-asert.md
> +#### REQ-ASERT-TARGET-COMPUTATION (target computation)
> > Having proper identifiers for requirements helps with referencing them.
> > The short form in English is in brackets.
> 
> I agree. It is a common practice in specs and standards.

No it absolutely is not. People reference section numbers in a specification. Zero RFCs do this. The C++ standard doesn't do this either.

I've never seen ANYTHING do this except some cobol code; which this specification seems to have more in common with.

2020-08-14 23:13 UTC, deadalnix commented on spec/2020-11-15-asert.md
> +ALGORITHM aserti3-2d is
+1 This is completely unreadable.

2020-08-14 23:15 UTC, deadalnix commented on spec/2020-11-15-asert.md
> +#### REQ-ASERT-TARGET-COMPUTATION (target computation)
This is not what has been done in this repository so this is going to be a hard no.

If you can make the case that it is worth doing, then please go over all existing spec and upgrade the style. This needs to be done in its own pull request as this is unrelated to the upgrade.

2020-08-14 23:22 UTC, schancel commented on spec/2020-11-15-asert.md
> +1. Choice of activation method
Agreed. Specifications do not typically contain rationale. Just details.

2020-08-14 23:41 UTC, jasonbcox commented on spec/2020-11-15-asert.md
> +ALGORITHM aserti3-2d is
The C++ implementation is already linked. If this pseudo-code doesn't provide any value, then we should just remove it.

2020-08-14 23:41 UTC, jasonbcox commented on spec/2020-11-15-asert.md
> +author: freetrader, Jonathan Toomim, Calin Culianu, Mark Lundeberg
No, this is at the bottom: `This specification is dual-licensed under the Creative Commons CC0 1.0 Universal and
GNU All-Permissive licenses.`
It really should be MIT licensed. This dual-licensing nonsense isn't necessary.

2020-08-14 23:41 UTC, jasonbcox commented on spec/2020-11-15-asert.md
> +#### REQ-ASERT-TARGET-COMPUTATION (target computation)
Splitting the targeting from the rest of the DAA spec? I don't follow.

2020-08-15 00:00 UTC, schancel commented on spec/2020-11-15-asert.md
> +    ; The following if-else construct is equivalent to `next_target ← floor(next_target * 2^factor)`
Sorry, I thought I was seeing this in `spec/2020-11-15-upgrade.md`

2020-08-15 00:00 UTC, schancel commented on spec/2020-11-15-asert.md
> +#### REQ-ASERT-TARGET-COMPUTATION (target computation)
Sorry, I thought I was reading this in `spec/2020-11-15-upgrade.md`

2020-08-15 03:50 UTC, Greg-Griffith commented on spec/2020-11-15-upgrade.md
> +## Coinbase Rule
ABC is not the reference implementation. any reference implementation title is one that you have bestowed upon yourself and is not true of the coin itself. Please remove your implementation specific details from this version of the coin spec.

2020-08-15 04:37 UTC, monsterbitar commented on spec/2020-11-15-upgrade.md
> +## Coinbase Rule
ABC is **NOT** a reference client, and have on multiple occasion stated that they support a multinode ecosystem, this rule is not supported by the ecosystem and should absolutely not be a part of this specification as a concensus change.

ABC can implement whatever they want in their node software, and put whatever information they want on websites they own, but if ABC wants to be a part of a multinode ecosystem they need to act like it, and not just say it is so.

2020-08-15 14:29 UTC, joshmg commented on spec/2020-11-15-upgrade.md
> +## Coinbase Rule
I do not see any support for this new coinbase rule from anywhere in the community outside of ABC, nor do I remember its merits ever being discussed in any post-May-2020 development meeting.  Therefore, Bitcoin Verde will not be implementing this change.  Furthermore, I do not believe it belongs in any specification claiming to be the "Bitcoin Cash specification" as it appears to be a rule unique to Bitcoin ABC.  I will not be including this new rule in the reference.cash nor bitcoinprotocol.cash specifications, however Bitcoin ABC is welcome to include it as a footnote under ABC-specific behavior if they so choose.

2020-08-15 14:45 UTC, BigBlockIfTrue commented on spec/2020-11-15-asert.md
> +#### REQ-ASERT-TARGET-COMPUTATION (target computation)
For your information, the [UAHF spec](https://github.com/bitcoincashorg/bitcoincash.org/blob/master/spec/uahf-technical-spec.md) contains a REQ-DISABLE and OPT-SERVICEBIT.

2020-08-15 16:08 UTC, jtoomim commented on spec/2020-11-15-upgrade.md
> +## Coinbase Rule
This does not belong in the BCH spec. Any full node that follows this rule will fork off from BCH.

2020-08-17 03:33 UTC, AndyChenW commented on spec/2020-11-15-upgrade.md
> +## Coinbase Rule
The spec is added into bitcoincash spec cos stupid Jihan give the domain to abc team, which I think only bitcoinabc.org should be owned by abc, bitcoincash should be owned by the non-dev like Cobra anonymously. Time to use a new domain, bye bye abc.

2020-08-17 17:16 UTC, Mengerian commented
@jasonbcox Tobias fixed many of the issues you commented on, you may want to check the latest version.

2020-08-17 17:51 UTC, jasonbcox commented on spec/2020-11-15-asert.md
> +ALGORITHM aserti3-2d is
Tobias has replaced this with a Python implementation. I think this is a reasonable choice given that it's concise.

2020-08-17 20:03 UTC, jasonbcox approved these changes
The spec has been cleaned up a bit now. Let's get it merged so we can start linking to it. Any further tweaks can be handled in future PRs.

2020-08-17 21:39 UTC, Mengerian commented
> The spec has been cleaned up a bit now. Let's get it merged so we can start linking to it. Any further tweaks can be handled in future PRs.

OK, will merge

2020-08-17 21:40 UTC, merged

2021-06-15 19:36 UTC, Desynkova commented on spec/2020-11-15-asert.md
> +```
bitcoin:bc1qutug350tmeruzcpdkdrl3pcnmpwuh22a5uwwae?amount=0.00001