Updates to nav bar
bitcoincashorg/bitcoincash.org pull request #546
Opened 2020-08-20 03:57 UTC by johnkuney

Replaced white logo with color versoin and made clickable
Style edits to price ticker
Rearrangment of nav items

2020-08-20 13:32 UTC, deadalnix requested changes
I have a few comments on the code, but also a more generic advice.

This is doing two things:
1/ Changing the logo in the nav bar so that is brings us back home + style.
2/ Changing the content of the menus.

By submitting both at the same time, you will impedes on your ability to iterate quickly in various ways:
1/ Larger patches are harder to review, and the larger the patch, the slower the review cycle will be.
2/ Any change required on one of the elements will prevent the other element from being merged.
3/ The longer the patch stays up, the more likely it is that you'll run into merge conflicts. Combined with 1 and 2, this compounds the slowdown.
4/ Large patches are harder to revert - for the same reason they cause more merge conflicts. This leads to more reluctance from reviewer to accept them, because the cost of error is greater.
5/ While this does not really apply to this patch, you might find yourself in a position where the people knowledgeable enough about the various parts of your patches are not the same, in which case the slowdown will be even more dramatic.

I recommend you red [this](https://medium.com/@kurtisnusbaum/large-diffs-are-hurting-your-ability-to-ship-e0b2b41e8acf) if you want to know more.

2020-08-20 13:32 UTC, deadalnix commented on v2/src/components/liveprice/live-price-widget.js
>          </div>
make sure that you run `npm run format` so that indentation gets fixed up.

2020-08-20 13:32 UTC, deadalnix commented on v2/src/layout/header.js
> +          </span> */}
Don't leave code commented out.

2020-08-20 13:32 UTC, deadalnix commented on v2/src/layout/header.js
> +  ]
That seem completely redundant. Why?

2020-08-20 13:32 UTC, deadalnix commented on v2/src/layout/header.js
> +    },
No need for both. Considering r/btc has turned into clown world, we probably want to go for r/bitcoincash only .

It is not clear to me that we want social media that high up. This is expensive real estate and comes at the price of getting links such as "get started" in a menu rather than right there.

Also, do we rally wnt to send things such as r/bitcoincash , Telegram, Facebook and so on for translation? I'm not convinced this is worth it, because these are brands.

2020-08-20 13:32 UTC, deadalnix commented on v2/src/layout/header.js
>      },
You link to services.html twice.

2020-08-20 13:32 UTC, deadalnix commented on v2/src/layout/header.js
> +            )}
Create an array with one item and then mapping over it here seems completely redundant.

2020-08-20 15:45 UTC, johnkuney commented on v2/src/components/liveprice/live-price-widget.js
>          </div>
Okay np ran that

2020-08-20 15:46 UTC, johnkuney commented on v2/src/layout/header.js
> +          </span> */}
removed

2020-08-20 15:46 UTC, johnkuney commented on v2/src/layout/header.js
> +  ]
Yeah not sure what I was doing there...fixed

2020-08-20 15:48 UTC, johnkuney commented on v2/src/layout/header.js
> +    },
Good points I thought maybe community channels were important to promote high up? But can the case for maybe leaving them in the footer. The resource tab was also getting quite long so I split out developer related items to its own tab which I think makes more sense and is a valid section to give prime spot to

2020-08-20 15:49 UTC, johnkuney commented on v2/src/layout/header.js
>      },
There is no histrory page yet so was an placeholder but I've replaced with the likely url

2020-08-20 15:54 UTC, johnkuney commented on v2/src/layout/header.js
> +            )}
Yeah thats unnecessary, fixed.
And overall I understand more and more now your work flow philosophy and its benefits. Sorry for taking a few times to catch up, but I guess I've been guilty of doing large changes in my past work. I think you'd be shocked at the size of diffs that happen at bitcoin.com sometimes lol. I will do my best to compartmentalize changes going forward.

2020-08-20 17:16 UTC, deadalnix requested changes

2020-08-20 17:16 UTC, deadalnix commented on v2/src/layout/header.js
> +            <div className={headerStyles.divider}></div>
Can you extract that part of the PR in its own PR?

2020-08-20 17:17 UTC, deadalnix requested changes
Please separate the different part of the PR.

2020-08-20 21:41 UTC, deadalnix requested changes
If you extract the ticker restyling, then this can also be merged directly, and that would leave this patch with only the decision about how the menu are structured. This would leave more room for someone like christabel to review that part and allow to move on other parts of the code.

2020-08-20 21:41 UTC, deadalnix commented on v2/src/layout/header.module.scss
> +}
Revert (or just run npm run format and it'll do it for you).

2020-08-20 22:42 UTC, deadalnix commented on v2/src/layout/header.js
>        text: (
You can do text: <World />

No need for a <></> wreapper is there is only one jsx element.

2020-08-20 22:42 UTC, johnkuney commented
Okay good point. I've backed out those remaining changes so now its just the nav items. Can revisit when Christabel gets back on that

2020-08-20 23:06 UTC, johnkuney commented on v2/src/layout/header.js
>        text: (
Good call, fixed

2020-08-24 14:47 UTC, johnkuney commented
Changing the nav to match the current site layout so there is not a difference between them in the interim when both sites are live. Its a weird UX if the nav changes from page to page. I've stashed the changes I had made and can add back in when it makes sense

2020-08-25 15:38 UTC, deadalnix requested changes

2020-08-25 15:38 UTC, deadalnix commented on v2/src/layout/header.js
> -    },
You can keep the whitepaper

2020-08-25 15:38 UTC, deadalnix commented on v2/src/layout/header.js
> -      href: "https://explorer.bitcoincash.org/",
IMO it is more valuable to have the explorer there than logos. Can we modify the old layout instead?

2020-08-25 23:00 UTC, deadalnix approved these changes

2020-08-25 23:00 UTC, deadalnix commented
Fantastic. I'm not so familiar with the legacy site, so I'll let @jasonbcox have a look before merging.

2020-08-26 13:02 UTC, merged