Announcement bar
bitcoincashorg/bitcoincash.org pull request #557
Opened 2020-08-25 16:48 UTC by johnkuney

Recreated announcement bar for information about network upgrades

2020-08-25 17:15 UTC, deadalnix requested changes

2020-08-25 17:15 UTC, deadalnix commented on v2/src/layout/page.js
> +      <AnnouncementBar />
Wouldn't that be better off in the header?

2020-08-25 17:15 UTC, deadalnix commented on v2/src/components/announcement-bar/announcement-bar.js
> +import React, { useState, useRef } from "react"
This is not really a reusable component. It belongs in layout.

2020-08-25 17:15 UTC, deadalnix commented on v2/src/components/announcement-bar/announcement-bar.js
> +function Accordion() {
This does not follow the style used by other components in the codebase.

2020-08-25 17:15 UTC, deadalnix commented on v2/src/components/announcement-bar/announcement-bar.js
> +            </a>
Why is one of these a button, and the other a raw link with a button class?

2020-08-25 17:15 UTC, deadalnix commented on v2/src/components/announcement-bar/announcement-bar.js
> +            <a
Use Link

2020-08-25 17:15 UTC, deadalnix commented on v2/src/components/announcement-bar/announcement-bar.js
> +            <a className={S.panelButton2} href="/spec/2020-11-15-upgrade.html">
Use Link

2020-08-25 17:15 UTC, deadalnix commented on v2/src/components/announcement-bar/announcement-bar.js
> +            <h4>Additional Information:</h4>
fbt

2020-08-25 17:15 UTC, deadalnix commented on v2/src/components/announcement-bar/announcement-bar.js
> +            <a
dito

2020-08-25 17:15 UTC, deadalnix commented on v2/src/components/announcement-bar/announcement-bar.js
> +import DismissBtn from "assets/images/close.png"
Button

2020-08-25 18:07 UTC, johnkuney commented on v2/src/layout/page.js
> +      <AnnouncementBar />
Yeah probably so, moved it

2020-08-25 18:12 UTC, johnkuney commented on v2/src/components/announcement-bar/announcement-bar.js
> +function Accordion() {
Unsure what you mean here?

2020-08-25 18:12 UTC, johnkuney commented on v2/src/components/announcement-bar/announcement-bar.js
> +import React, { useState, useRef } from "react"
moved

2020-08-25 18:12 UTC, johnkuney commented on v2/src/components/announcement-bar/announcement-bar.js
> +            </a>
changed to button

2020-08-26 12:30 UTC, deadalnix commented on v2/src/layout/announcement-bar/announcement-bar.js
> +function Accordion() {
This still doesn't use the same style as the rest of the codebase.

2020-08-26 12:30 UTC, deadalnix commented on v2/src/layout/announcement-bar/announcement-bar.js
> +  const [setActive, setActiveState] = useState("")
setActive is not an appropriate name for a value. As a general rule, you want value to be nouns and function to be verbs. You are using a verb for a value. Value do not do anything.

2020-08-26 12:30 UTC, deadalnix commented on v2/src/layout/announcement-bar/announcement-bar.js
> +  const [setDismiss, setDismissState] = useState("")
dito for all others.

2020-08-26 17:01 UTC, johnkuney commented on v2/src/layout/announcement-bar/announcement-bar.js
> +  const [setActive, setActiveState] = useState("")
Okay makes sense, I've renamed them and cleaned it up a bit

2020-08-28 16:44 UTC, deadalnix requested changes

2020-08-28 16:44 UTC, deadalnix commented on v2/src/layout/announcement-bar/announcement-bar.js
> +  const [DismissStyle, setDismiss] = useState("")
Capitalized identifier refers to enum's values or JSX components names. Variables are not capitalized.

2020-08-28 16:44 UTC, deadalnix commented on v2/src/layout/announcement-bar/announcement-bar.js
> +  }
So, it seems like the thing has two states: active/inactive and dismissed/not ismissed. Is that correct? if so, there there should be two states and they should be booleans. If that is not correct, then what is the expected behavior here?

2020-08-28 16:44 UTC, deadalnix commented on v2/src/layout/announcement-bar/announcement-bar.js
> +  function toggleAccordion() {
These function do not match the style of the codebase either.

2020-08-28 16:44 UTC, deadalnix commented on v2/src/layout/announcement-bar/announcement-bar.js
> +      State === "active" ? "0px" : `${content.current.scrollHeight}px`
What this is doing would warrant some comments.

2020-08-28 17:38 UTC, johnkuney commented
Okay I went ahead and simplified by using the react bootstrap accordion instead

2020-08-31 17:06 UTC, johnkuney commented on v2/src/layout/announcement-bar/announcement-bar.js
> +const AccordionComponent = () => {
For sure

2020-08-31 17:06 UTC, johnkuney commented on v2/src/layout/announcement-bar/announcement-bar.js
> +          </svg>
Yeah good idea, added the file

2020-08-31 17:06 UTC, johnkuney commented on v2/src/layout/announcement-bar/announcement-bar.js
> +                  href={"/roadmap"}
fixed

2020-08-31 17:07 UTC, johnkuney commented on v2/src/layout/announcement-bar/announcement-bar.js
> +              <Accordion.Toggle as={S.primaryButton}>
I put it there so the accordion will close when click through to roadmap. Otherwise it stays open

2020-08-31 17:07 UTC, johnkuney commented on v2/src/layout/announcement-bar/announcement-bar.js
> +                  <fbt desc="close button">Close</fbt>
improved

2020-09-01 12:48 UTC, deadalnix approved these changes
This looks good to me now. Can you doubl check you formatted? Some of the lines seems very long.

2020-09-01 12:48 UTC, deadalnix commented on v2/src/layout/announcement-bar.js
> +import S from "./announcement-bar.module.scss"
This is handy. Maybe that should be an idiom.

2020-09-01 13:52 UTC, johnkuney commented
Ah good eye. I guess I hadn't after I changed an fbt description and it was long enough to break it out

2020-09-01 13:59 UTC, merged