Getting started page
bitcoincashorg/bitcoincash.org pull request #564
Opened 2020-08-27 17:32 UTC by johnkuney

adding getting started page
- added react-bootstrap to build for help with formatting as old site using bootstrap and makes for quick grid layout

2020-08-28 11:28 UTC, deadalnix requested changes

2020-08-28 11:28 UTC, deadalnix commented on v2/src/pages/start-here.js
> +                    What is peer to peer electronic cash?{" "}
remove trainling space

2020-08-28 11:28 UTC, deadalnix commented on v2/src/pages/start-here.js
> +              <Link to="getting-started.html">
/getting-started.html

2020-08-28 11:28 UTC, deadalnix commented on v2/src/pages/start-here.js
> +                  buttonText={fbt("View More", "'View More' button")}
this description is not going to help translators.

2020-08-28 11:28 UTC, deadalnix commented on v2/src/pages/start-here.js
> +                  {" "}
Remove spaces

2020-08-28 11:28 UTC, deadalnix commented on v2/src/pages/start-here.js
> +                  {" "}
dito

2020-08-28 11:28 UTC, deadalnix commented on v2/src/pages/start-here.js
> +                  {" "}
remove

2020-08-28 11:28 UTC, deadalnix commented on v2/src/pages/start-here.js
> +              <Link to="spend-bitcoin-cash.html">
/spend-bitcoin-cash.html

2020-08-28 11:28 UTC, deadalnix commented on v2/package.json
> +    "react-bootstrap": "^1.3.0",
Good call!

2020-08-28 14:35 UTC, johnkuney commented on v2/src/pages/start-here.js
> +                    What is peer to peer electronic cash?{" "}
done

2020-08-28 14:36 UTC, johnkuney commented on v2/src/pages/start-here.js
> +              <Link to="getting-started.html">
Okay fixed

2020-08-28 14:36 UTC, johnkuney commented on v2/src/pages/start-here.js
> +                  buttonText={fbt("View More", "'View More' button")}
fixed

2020-08-28 14:36 UTC, johnkuney commented on v2/src/pages/start-here.js
> +                  {" "}
done

2020-08-28 14:36 UTC, johnkuney commented on v2/src/pages/start-here.js
> +                  {" "}
done

2020-08-28 14:36 UTC, johnkuney commented on v2/src/pages/start-here.js
> +                  {" "}
removed

2020-08-28 14:36 UTC, johnkuney commented on v2/src/pages/start-here.js
> +              <Link to="spend-bitcoin-cash.html">
fixed

2020-08-28 15:34 UTC, merged

2024-12-10 15:50 UTC, PlatinumWrist5055 reviewed
This been reviewed