Getting started content page
bitcoincashorg/bitcoincash.org pull request #565
Opened 2020-08-28 02:56 UTC by johnkuney

Adding page for getting started content
- made reusable components for the side bar and main tile as the other pages uses these as well

2020-08-28 11:14 UTC, deadalnix requested changes
Minor changes, but looks good overall.

2020-08-28 11:14 UTC, deadalnix commented on v2/src/components/large-tile/large-tile.js
> +    <>
No need for empty jsx

2020-08-28 11:14 UTC, deadalnix commented on v2/src/components/large-tile/large-tile.js
> +}
There is a lot of duplication between the two codepath. You can put the content that is inside and change depending on the presence of a video in local variables.

2020-08-28 11:14 UTC, deadalnix commented on v2/src/components/sidebar/sidebar.js
> +    <>
No need for the empty JSX.

2020-08-28 15:00 UTC, johnkuney commented on v2/src/components/large-tile/large-tile.js
> +    <>
fixed

2020-08-28 15:01 UTC, johnkuney commented on v2/src/components/large-tile/large-tile.js
> +}
Good call, condensed it some

2020-08-28 15:01 UTC, johnkuney commented on v2/src/components/sidebar/sidebar.js
> +    <>
fixed

2020-08-28 16:20 UTC, deadalnix requested changes

2020-08-28 16:20 UTC, deadalnix commented on v2/src/components/sidebar/sidebar.js
> +            return (
When the lambda only return, you can `content.map((item, i) => returnValue`

2020-08-28 16:20 UTC, deadalnix commented on v2/src/pages/getting-started.js
> +            video={true}
This seems to be the only instance where this component is used. Are there others planned? If not, making a component out of it seems like it not necessary. In general, it also beg the question of have tweaks and nobs which are not used.

2020-08-28 16:20 UTC, deadalnix commented on v2/src/pages/getting-started.js
> +    },
Does it ever make sense that there would be more elements in there? If not then the whole design is a bit strange. It's unclear to me what the LargeTile abstraction provides. It doesn't seems seems like there is a clear boundary between what belong here and what belond in large tile because it doesn't really have a well defined role.

If its role is just to create a large tile, like its name indicate, then why does it know about the video or other stuffs for instance?

2020-08-28 16:36 UTC, johnkuney commented on v2/src/components/sidebar/sidebar.js
> +            return (
Sorry not sure what you mean here

2020-08-28 16:37 UTC, johnkuney commented on v2/src/pages/getting-started.js
> +            video={true}
Yes it will be on like 5 pages. The different tweaks are just because of the current legacy content. One of them has a video and the rest an image. And same for the button, only one has a button

2020-08-28 16:43 UTC, johnkuney commented on v2/src/pages/getting-started.js
> +    },
My main reasoning for that abstraction was to make the code more readable/easy to add content. I wanted to separate out the long text items from the LargeTile call, and like I said above the video and button specification is because only one of the pages will have that currently. Maybe an overcomplicated solution, but it will be used on five pages and now can just plug in the text and image for the rest of them, and there wont need to be a seperate CSS module for each page, it can all be contained in the large tile component

2020-08-28 16:48 UTC, johnkuney commented on v2/src/pages/getting-started.js
> +    },
and yes I guess this page will have more content than the others https://www.bitcoincash.org/buy-bitcoin-cash.html and if we want to add more paragraphs or text in the future could be handy...

2020-08-31 16:06 UTC, deadalnix commented on v2/src/components/sidebar/sidebar.js
> +            return (
See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions

Notably the exemple:

```
materials.map(material => material.length)

// And not
materials.map(material => {
    return material.length
})
```

The second option is correct too, but a bit clumsy.

2020-08-31 16:08 UTC, deadalnix commented on v2/src/pages/getting-started.js
> +            video={true}
Then the simplest path forward seems to be to create a component and pass either the image or video as children. If there is a common pattern that emerges for children, nothing prevents us from adding another component that specialize for this pattern of children.

2020-08-31 16:11 UTC, deadalnix commented on v2/src/pages/getting-started.js
> +    },
ok.

2020-08-31 18:13 UTC, johnkuney commented on v2/src/components/sidebar/sidebar.js
> +            return (
okay for sure reformatted that

2020-08-31 18:13 UTC, johnkuney commented on v2/src/pages/getting-started.js
> +            video={true}
Yeah thats cleaner, made the update

2020-09-01 13:27 UTC, deadalnix requested changes
This is mostly good. A few details to polish and this is good to go.

2020-09-01 13:27 UTC, deadalnix commented on v2/src/pages/getting-started.js
> +        "Peer to peer (P2P) electronic cash is simply described as online money sent from one person to another without the need for a trusted third-party. As described in the original Bitcoin whitep
This is quite long. If `npm run format` is unable to break it, I would advice to use a `<fbt>` tag instead.

2020-09-01 13:27 UTC, deadalnix commented on v2/src/pages/getting-started.js
> +            ></iframe>
Can't a self closing tag be used here?

2020-09-01 14:08 UTC, merged