Wallets page
bitcoincashorg/bitcoincash.org pull request #575
Opened 2020-09-02 04:41 UTC by johnkuney

Adding wallets page. Had to tweak some of the components to improve styling, and all of the images for the different wallets are being pulled from the static file in the root to avoid having to import each image in the page

2020-09-02 13:38 UTC, deadalnix requested changes

2020-09-02 13:38 UTC, deadalnix commented on v2/src/pages/wallets.js
> +      img: "/images/wallets/bitcoindotcom.png",
Given the choice, it is better to use import rather than static assets, so that webpack can do its magic.

2020-09-02 13:38 UTC, deadalnix commented on v2/src/pages/wallets.js
> +          Paper{" "}
Desktop/Hardware &al need to be translated - and in fact, re on the original website, so if you do it the same way, they should translate automatically here once transifex figure it out.

It is usually not possible to translate one word at once, because language do not have 1:1 mapping between words.

2020-09-02 17:12 UTC, johnkuney commented on v2/src/pages/wallets.js
> +      img: "/images/wallets/bitcoindotcom.png",
Yeah I guess so. Got them imported

2020-09-02 17:16 UTC, johnkuney commented on v2/src/pages/wallets.js
> +          Paper{" "}
Okay for sure. Yeah its weird I did it like that because thats how it is on legacy site in that particular area. They only have a translation string for the word 'wallet' and then the adjectives are just left in english. But then I just saw above it in the side bar the whole term is translated. Anyway fixed it here and it should pick up the translation from legacy site

2020-09-02 22:48 UTC, deadalnix requested changes

2020-09-02 22:48 UTC, deadalnix commented on v2/src/pages/wallets.js
> +import Bitcoincashnotes from "assets/images/wallets/bitcoincashnotes.png"
So, this is clearly not going to scale or be maintainable in anyway. What about this:

1. Create a 'src/partners/wallets' folder
2. create a js file for each wallet that default export the following datastructure:
```
    {
      link: ...,
      alt: ...,
      img: ...,
      android: ...,
      ios: ...,
      windows: ...,
    },
```
3. Store the images next to the js file.
4. Use gatsby-source-filesystem to enable getting the list of all the wallets.
5. In this file, use a graphql query to query the list of wallets.
6. Go over all the wallet and construct the page.

Now we can add a new file to add a wallet, or remove one.

2020-09-03 04:25 UTC, johnkuney commented on v2/src/pages/wallets.js
> +import Bitcoincashnotes from "assets/images/wallets/bitcoincashnotes.png"
Sorry may need some help with that idea. I follow the logic but not entirely sure how to execute....Was able to get a folder setup and add a gatsby-source-filesystem option to the config so it can be queried , but not exactly sure on the rest of the steps....

2020-09-03 11:39 UTC, deadalnix commented on v2/src/pages/wallets.js
> +import Bitcoincashnotes from "assets/images/wallets/bitcoincashnotes.png"
OK, I'm not gatsby expert, but I will give it a go.

2020-09-03 11:40 UTC, merged