Refactor sharable logic in gatsby-node
bitcoincashorg/bitcoincash.org pull request #580
Opened 2020-09-03 17:03 UTC by jasonbcox

This is in preparation for new `createPages` logic that will generate some pages and/or redirects based on frontmatter. `createPages` can share some of the localization logic used by `onCreatePage`, so this patch refactors to make it available.

There is no change in behavior.

2020-09-03 22:20 UTC, deadalnix requested changes
This is a good idea to start to extract the components that work on their own.

I think think you current decoupage illustrate pretty well why your previous approach was poorly structured. Especially the branching in the middle of `createPageForAllLocales` . I'm fairly confident that you only felt the need to extract `localizePath` as a workaround for this choice.

2020-09-03 22:20 UTC, deadalnix commented on v2/gatsby-node.js
> +      if (createFn) {
No need to branch here.

2020-09-03 22:20 UTC, deadalnix commented on v2/gatsby-node.js
> +      const pathWithLocale = localizePath(originalPath, params)
That would be the `loalizedPath` ?

2020-09-03 22:20 UTC, deadalnix commented on v2/gatsby-node.js
> +}
It seems doubtful that this is useful on its own. This most likely translate a design problem in what you got coming down the road.

2020-09-03 22:20 UTC, deadalnix commented on v2/gatsby-node.js
> +async function createPageForAllLocales(createPage, page, createFn) {
Use the lambda style syntax like in the rest of the codebase.

2020-09-04 21:28 UTC, jasonbcox commented on v2/gatsby-node.js
> +}
I need a way to localize the v1 path override. An alternative would be to pass a localization prefix to createFn, but this makes a stronger assumption that localized paths will always be prefix-only.

2020-09-05 00:20 UTC, deadalnix requested changes

2020-09-05 00:20 UTC, deadalnix commented on v2/gatsby-node.js
> +}
You don't if you start from the localized path remove the trailing slash and add ".html"

2020-09-05 00:20 UTC, deadalnix commented on v2/gatsby-node.js
> +      if (createFn) {
This still does not make sense.

2020-09-07 15:15 UTC, jasonbcox commented on v2/gatsby-node.js
> +}
...localize the v1 path **override**, not the default behavior.

2020-09-07 15:40 UTC, jasonbcox commented on v2/gatsby-node.js
> +      const pathWithLocale = localizePath(originalPath, params)
It looks too similar to the function name `localizePath` so I renamed it to another appropriate name.
Alternative is `const localizedPath = addLocaleToPath(...)`

2020-09-07 15:41 UTC, jasonbcox commented on v2/gatsby-node.js
> +      const pathWithLocale = localizePath(originalPath, params)
This naming is actually strictly more correct, so let's go with that.

2020-09-07 16:27 UTC, deadalnix commented on v2/gatsby-node.js
> +}
Do we actually need a v1 path override? Can we add it if/when we need it?

2020-09-09 02:00 UTC, deadalnix requested changes

2020-09-09 02:00 UTC, deadalnix commented on v2/gatsby-node.js
> +}
This ^

2020-09-09 18:20 UTC, jasonbcox commented on v2/gatsby-node.js
> +}
We can add it when needed. The whole point of adding it up-front was to ensure low-friction for fixing routing issues that may appear in production.

2020-09-09 21:22 UTC, deadalnix commented on v2/gatsby-node.js
> +}
That's also how you end up with this marvel: https://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/aop/framework/AbstractSingletonProxyFactoryBean.html

You'll note that it makes things easier if things evolve in a way you expected, but also makes things worse when thing evolve in a way you did not expect.

2020-09-09 21:22 UTC, merged