adding spend page
bitcoincashorg/bitcoincash.org pull request #581
Opened 2020-09-04 17:38 UTC by johnkuney

2020-09-04 21:05 UTC, deadalnix requested changes

2020-09-04 21:05 UTC, deadalnix commented on v2/src/assets/icons/spend/cart.svg
> +<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 512 512'><circle cx='176' cy='416' r='16' style='fill:none;stroke-linecap:round;stroke-linejoin:round;stroke-width:32px'/><circle cx='400' cy='416
Just like for accept, we'd be better off with some kind of icon repository rather than having them grouped by page.

2020-09-04 21:05 UTC, deadalnix commented on v2/src/layout/global.scss
> +.spendmap {
This seems to be spend specific, why not create a css module for that page?

2020-09-04 22:13 UTC, johnkuney commented on v2/src/layout/global.scss
> +.spendmap {
Oh yeah sure, added

2020-09-05 00:14 UTC, deadalnix commented on v2/src/assets/icons/spend/cart.svg
> +<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 512 512'><circle cx='176' cy='416' r='16' style='fill:none;stroke-linecap:round;stroke-linejoin:round;stroke-width:32px'/><circle cx='400' cy='416
It seems like this is the same shopping cart, so it's actually better to not duplicate it.

2020-09-05 00:16 UTC, deadalnix requested changes

2020-09-05 00:16 UTC, deadalnix commented on v2/src/pages/spend-bitcoin-cash.js
> +        <h2 className="centerh2">
S.centerh2

If this changes nothing, then maybe this can simply be removed?

2020-09-05 01:04 UTC, johnkuney commented on v2/src/pages/spend-bitcoin-cash.js
> +        <h2 className="centerh2">
ah no need it to center the text. I've combined with the other class to simplify

2020-09-05 01:05 UTC, johnkuney commented on v2/src/assets/icons/spend/cart.svg
> +<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 512 512'><circle cx='176' cy='416' r='16' style='fill:none;stroke-linecap:round;stroke-linejoin:round;stroke-width:32px'/><circle cx='400' cy='416
Cart should be good now

2020-09-06 22:06 UTC, deadalnix requested changes

2020-09-07 13:34 UTC, johnkuney commented on v2/src/pages/spend-bitcoin-cash.js
> +          <h4 className={S.center}>
Sure, updated

2020-09-07 16:28 UTC, merged