adding accept page
bitcoincashorg/bitcoincash.org pull request #582
Opened 2020-09-04 17:58 UTC by johnkuney

adding accept-bitcoin-cash page

2020-09-04 21:04 UTC, deadalnix requested changes
A small change, but overall, LGTM

2020-09-04 22:21 UTC, johnkuney commented on v2/src/assets/icons/accept/calculator.svg
> +<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 512 512'><title>ionicons-v5-d</title><rect x='112' y='48' width='288' height='416' rx='32' ry='32' style='fill:none;stroke-linecap:round;stroke-li
Okay moved them. Please merge the Spend page PR first though due to cart icon repetition

2020-09-05 00:17 UTC, deadalnix submitted a review, later dismissed
I wish I could merge this, but the cart is missing.

2020-09-05 00:17 UTC, deadalnix commented on v2/src/pages/accept-bitcoin-cash.js
> +import Cart from "assets/icons/cart.svg"
This file is missing.

2020-09-05 00:59 UTC, johnkuney commented on v2/src/pages/accept-bitcoin-cash.js
> +import Cart from "assets/icons/cart.svg"
whoops okay its in there now

2020-09-05 01:09 UTC, merged