Buy page
bitcoincashorg/bitcoincash.org pull request #585
Opened 2020-09-05 04:05 UTC by johnkuney

adding buy page

2020-09-05 12:25 UTC, deadalnix requested changes

2020-09-05 12:25 UTC, deadalnix commented on v2/src/partners/exchanges/alfacashier.js
> +import AlfacashierLogo from "./images/alfacashier.png"
Putting the image in the same folder as the js was very helpfull to remove a ton of dead images in the wallet list. You should consider doing the same here.

2020-09-05 12:25 UTC, deadalnix commented on v2/src/partners/exchanges/bithumb.js
> +const Bithumb = () => ({
Some have a line here, some do not. You might want to make this uniform.

2020-09-05 15:36 UTC, johnkuney commented on v2/src/partners/exchanges/alfacashier.js
> +import AlfacashierLogo from "./images/alfacashier.png"
For sure, I did go through and only copy over active images, so shouldnt be any dead images in there

2020-09-05 15:36 UTC, johnkuney commented on v2/src/partners/exchanges/bithumb.js
> +const Bithumb = () => ({
For sure, its uniform now

2020-09-06 22:05 UTC, deadalnix requested changes

2020-09-06 22:07 UTC, deadalnix requested changes

2020-09-06 22:07 UTC, deadalnix commented on v2/src/pages/buy-bitcoin-cash.js
> +          <a href="https://free.bitcoin.com/" style={{ color: "#f7941c" }}>
Why is there a color specific for this link?

2020-09-07 14:08 UTC, johnkuney commented on v2/src/partners/exchanges/alfacashier.js
> +import AlfacashierLogo from "./images/alfacashier.png"
Okay fair enough, makes sense. Updated

2020-09-07 14:08 UTC, johnkuney commented on v2/src/partners/exchanges/houbi.js
> +const Houbi = () => ({
fixed

2020-09-07 14:12 UTC, johnkuney commented on v2/src/pages/buy-bitcoin-cash.js
> +          <a href="https://free.bitcoin.com/" style={{ color: "#f7941c" }}>
That was just the color used on the legacy page sidebar link, but I've updated to the theme orange. Also cleaned this up a bit by putting the style in the sidebar instead of inline

2020-09-07 18:17 UTC, deadalnix requested changes

2020-09-07 18:17 UTC, deadalnix commented on v2/src/pages/buy-bitcoin-cash.js
> +          <a href="https://www.bitcoincash.org/spend-bitcoin-cash.html">
You need to fix this. Use a Link tag (in fact, you should probably use a Link tag in most places instead of raw a tags) and use a link that does not depend on the domain.

2020-09-07 19:12 UTC, johnkuney commented on v2/src/pages/buy-bitcoin-cash.js
> +          <a href="https://www.bitcoincash.org/spend-bitcoin-cash.html">
For sure. fixed

2020-09-07 23:28 UTC, merged