Mobile menu style fixes
bitcoincashorg/bitcoincash.org pull request #602
Opened 2020-09-16 05:48 UTC by johnkuney

2020-09-16 15:44 UTC, jasonbcox requested changes

2020-09-16 15:44 UTC, jasonbcox commented on v2/src/layout/header.js
> +  function MobileDropdown({ children, links, navLinkClass }) {
Why introduce a copy of the existing MobileDropdown instead of fixing the existing one? As far as I can tell, the one in `components/dropdownButtons/dropdown` is no longer used now.

2020-09-16 16:23 UTC, johnkuney commented on v2/src/layout/header.js
> +  function MobileDropdown({ children, links, navLinkClass }) {
For sure, cleaned that up. I moved it to the header so I could trigger the collapse state of the whole menu when language is selected. Otherwise could only close the language menu

2020-09-16 18:51 UTC, deadalnix requested changes

2020-09-16 18:51 UTC, deadalnix commented on v2/src/layout/header.js
> +  function MobileDropdown({ children, links, navLinkClass }) {
The fact you need to track the dropdown state in the header rather than the dropdown is a good indication that there is already too much in the header. You are making the problem worse.

Ultimately, why is this the header's job to know if the dropdown is mobile or not or what? The header ask for a dropdown, it's up to the drop down component to sort this mess out.

2020-09-17 03:28 UTC, johnkuney commented on v2/src/layout/header.js
> +  function MobileDropdown({ children, links, navLinkClass }) {
Good points. I've refactored a bit and separated the components

2020-09-17 14:47 UTC, deadalnix requested changes

2020-09-17 14:47 UTC, deadalnix commented on v2/src/layout/header.js
> +        setCurrentUSDPrice(response.data.USD.toFixed(2))
This has nothing to do with the patch at hand.

2020-09-17 14:47 UTC, deadalnix commented on v2/src/layout/header.js
> +          <MobileNavItems navBarItems={navBarItems} />
Either this is some kind of generic component that generate a navbar, in which case it's hard to justify this components having to deal with the fact that navbar for mobile or desktop des things differently, or it is not generic, and then it is hard to justify that this is the pieces of code that needs to handle what is in the navbar.

You really need to think about what is responsible of what and split things accordingly.

2020-09-17 16:04 UTC, johnkuney commented on v2/src/layout/header.js
> +          <MobileNavItems navBarItems={navBarItems} />
Can you help me understand this? I would say the header component is not generic. So....there shouldnt be seperate components for the NavItems and MobileNavItems? Or both of those should be directly in the header?

2020-09-18 01:21 UTC, deadalnix commented on v2/src/layout/header.js
> +          <MobileNavItems navBarItems={navBarItems} />
You need to decide what the responsibility of each piece of code is and split things accordingly.

2020-09-20 15:00 UTC, deadalnix requested changes
This is now doing 20 different things at once.

This to split this up in meaningful chunks.

2020-09-21 16:07 UTC, johnkuney commented
Are you talking about this PR or the nav components?

2020-09-21 21:17 UTC, deadalnix commented
I'm talking about the fact that this very PR now does a ton of stuff. It can be broken down.

2020-09-21 21:34 UTC, johnkuney commented
Okay for sure. It got a bit carried away because the whole header component needed rearragning to achieve the original goal of improving mobile nav UX. I'll break it up

2020-09-21 23:33 UTC, deadalnix commented
Don't be worried, this is a normal part of the process. You start pulling the string, a whole ball of stuff comes with it, you deal with it. Now is the time to break it up. For instance, there are refactoring in there - changes in the structure of the code that do not change the behavior. You might want to extract these in their own patch, and then you can apply the behavioral changes on top of it.

2020-09-22 03:24 UTC, johnkuney commented
Okay broke these changes out into other PRs. I'll close this PR to avoid confusion

2020-09-22 03:24 UTC, closed without merging