CSS fix on links in sidebar
bitcoincashorg/bitcoincash.org pull request #604
Opened 2020-09-17 02:00 UTC by johnkuney

2020-09-17 14:38 UTC, deadalnix commented
What problem does this solve?

2020-09-17 15:42 UTC, johnkuney commented
Sorry should have left a description. Just a style patch for the links that are in the sidebar component in the getting started pages (/buy-bitcoin-cash/ ex) The text links within the paragraph needed to be specified to inline so they dont break lines

2020-09-17 16:08 UTC, jasonbcox requested changes
This breaks the rendering of the sidebar container in Firefox 68.12.x and I still see breaking of some of the lines since they're way too long to fit on one line. I'm not sure why forcing them to not break is beneficial.

2020-09-17 16:33 UTC, johnkuney commented
I said the wrong word. I want the links to break. Currently they take an entire line of the paragraph like you are describing above. By making them inline they should flow with the paragraph right? I'm seeing the opposite of what youre describing with this change. Are you seeing that running this or thats what you see on the live site?

2020-09-17 16:46 UTC, deadalnix commented
Ok so your problem is that the sidebar display are defined as flex, which is good, but every child is also defined as flex, which is definitely wrong. You need to fix the sidebar CSS instead of doing this.

2020-09-17 16:49 UTC, deadalnix commented
You want to change this into `.card > a` or something like that.

2020-09-17 17:10 UTC, johnkuney commented
Okay I specified a class for the links that need flex so it doesnt get applied to the others

2020-09-17 18:57 UTC, jasonbcox submitted a review, later dismissed

2020-09-18 00:58 UTC, deadalnix commented
> 
> 
> You want to change this into `.card > a` or something like that.

2020-09-18 01:00 UTC, deadalnix requested changes
You don't need to add a new class or anything. See comment I made twice now.

2020-09-18 01:22 UTC, johnkuney commented
this doesnt work for the rows that need to be links on the wallet page

2020-09-18 01:22 UTC, johnkuney commented
those are a children too and need specific style

2020-09-18 01:23 UTC, deadalnix requested changes
I don't think we have clickableRow anywhere in the codebase at this time, so i don't see how that CSS element makes any sense.

2020-09-18 01:23 UTC, deadalnix commented on v2/src/components/sidebar/sidebar.module.css
> +.clickableRow:hover {
Why is this clickableRow now?

2020-09-18 01:23 UTC, johnkuney commented on v2/src/components/sidebar/sidebar.module.css
> +.clickableRow:hover {
thats the class name

2020-09-18 01:24 UTC, deadalnix commented
This is wrong: https://github.com/bitcoincashorg/bitcoincash.org/pull/604/files#diff-c084369006e972f978373026b3dc660cR14

It defines all the childs as flew too.

2020-09-18 01:25 UTC, johnkuney commented
yes thats why I added the class before. Some of the links in the sidebar need different styling

2020-09-18 13:36 UTC, deadalnix commented
There are no other links in your patch that use the class, so I still don't see how any of this makes any sense.

2020-09-18 13:56 UTC, johnkuney commented
There are two possible types of links that need different styling in this sidebar component. 

One is the type that I made this class for. It needs display: flex some colors etc. These are the anchor links that take you to different sections found on the wallet page for example that take up a whole row.

The other type is a link within the paragraph text. These only need their color defined and the rest of the default styling is fine. So I selected them through their parent class and applied the color no class needed

2020-09-18 23:24 UTC, deadalnix commented
The anchor links are not immediate childs of .card are they?

The these anchor link cannot appear anywhere else. So why `.card > a` inadequate?

2020-09-18 23:52 UTC, johnkuney commented
The anchor links are not direct children of .card. They are children of .cardIconRow so .cardIconRow > a works

2020-09-19 13:34 UTC, merged