Fix twitter card image path
bitcoincashorg/bitcoincash.org pull request #609
Opened 2020-09-22 03:21 UTC by johnkuney

I realized twitter card image needs an absolute path to work. So used the static folder and referenced the url directly. 
- moved twitter image to static folder
- added bitcoincash.org url + file path to twitter image so it will work when live on bitcoincash.org

2020-09-22 12:56 UTC, deadalnix requested changes
Why dos it need an absolute path to work?

2020-09-22 12:56 UTC, deadalnix commented on v2/src/components/seo.js
> +          content: "https://www.bitcoincash.org/images/" + metatwitterImage,
Do not bake the domain in the code

2020-09-22 13:56 UTC, johnkuney commented
You'd have to ask twitter, but its stated in this thread https://twittercommunity.com/t/card-error-unable-to-render-or-no-image-read-this-first/62736 third from last bullet

2020-09-22 14:05 UTC, johnkuney commented on v2/src/components/seo.js
> +          content: "https://www.bitcoincash.org/images/" + metatwitterImage,
For sure. What about if we define it in the gatsby config meta data and bring it in like that?

2020-09-22 14:27 UTC, deadalnix requested changes
So, I've loaded the site from the branch in your repo. I can't see anything different in either chrome or firefox.

It remains unclear what problem this is solving if any, and, in any case, the solution needs to adjust to the source from which the content is served.

2020-09-22 14:27 UTC, deadalnix commented on v2/gatsby-config.js
> +    siteURL: "https://www.bitcoincash.org/",
I don't see how putting the absolute url somewhere else solves anything.

2020-09-22 20:46 UTC, johnkuney commented
So this problem is as of now this twitter card image is not working with twitter. You can test it out here https://cards-dev.twitter.com/validator

According to their docs the image needs an absolute path to work

So need to define the absolute path. I agree having it adjust to the serving source is ideal. Will see if I can make that happen

2020-09-22 21:15 UTC, johnkuney commented
hmm may be stuck with it. Seems gatsbys own docs recomend defining the domain since gatsby cant really see it 
<img width="808" alt="Screen Shot 2020-09-22 at 4 04 54 PM" src="https://user-images.githubusercontent.com/31288518/93938390-ca059180-fcee-11ea-851c-036dfcce5df5.png">

2020-09-22 21:54 UTC, deadalnix commented
Alright, but then it mean that passing the twitter image as argument is not going to work, so we got to remove that option.

2020-09-22 21:56 UTC, deadalnix requested changes
One small change and this can be merged.

2020-09-22 21:56 UTC, deadalnix commented on v2/src/components/seo.js
> +          content: "https://www.bitcoincash.org/images/" + metatwitterImage,
OK so it seems like there is no good way to do this. Then I guess we can go with this.

Can you set the images/ as part of metatwitterImage rather than prebaked?

2020-09-23 00:28 UTC, johnkuney commented
Okay made that edit. Was that other comment still relevant? It looks to me we can still use the argument. Will just need to pass a string of the image path wanted. Seems to work in testing

2020-09-23 13:33 UTC, merged