Add upgrade page
bitcoincashorg/bitcoincash.org pull request #617
Opened 2020-09-24 19:56 UTC by johnkuney

Creating v2 page for /upgrade. Carries over same info as legacy page plus additional link to blog post as requested

2020-09-24 23:09 UTC, deadalnix requested changes

2020-09-24 23:09 UTC, deadalnix commented on v2/src/pages/upgrade.js
> +            "'See Roadmap' button of the annoucement bar"
It's not the announcement bar :)

2020-09-24 23:09 UTC, deadalnix commented on v2/src/pages/upgrade.js
> +          <fbt desc="Annoucement bar inner headline">
dito

2020-09-24 23:09 UTC, deadalnix commented on v2/src/pages/upgrade.js
> +  })
Don't duplicate logic, factorize instead.

2020-09-25 02:04 UTC, johnkuney commented on v2/src/pages/upgrade.js
> +            "'See Roadmap' button of the annoucement bar"
ah for sure, changed

2020-09-25 02:04 UTC, johnkuney commented on v2/src/pages/upgrade.js
> +          <fbt desc="Annoucement bar inner headline">
fixed

2020-09-25 02:05 UTC, johnkuney commented on v2/src/pages/upgrade.js
> +  })
yeah good call. Made a global helper for this and added to the announcement bar as well. That work?

2020-09-25 14:32 UTC, merged