Footer update
bitcoincashorg/bitcoincash.org pull request #627
Opened 2020-09-29 20:23 UTC by johnkuney

The footer was pretty basic so I wanted to fill it out to more of a traditional footer with links to pages. 
- Added bitcoin cash logo and moved copyright text up
- added three columns of page categories with links
- updated telegram logo

2020-09-30 07:07 UTC, deadalnix requested changes

2020-09-30 07:07 UTC, deadalnix commented on v2/src/layout/footer.js
> +  ]
This seems to be the exact same thing as in the top menu, so you need to factor it.

2020-10-01 02:33 UTC, johnkuney commented on v2/src/layout/footer.js
> +  ]
Okay I made some adjustments so the header and footer can pull from the same source of links. Only issue is I cannot get it to work with <fbt>? So as it is it is not ready to merge, but works without fbt. Obviously need to fix that though...

Do you have any ideas why it might be breaking with fbt items in the arrays?

2020-10-01 08:41 UTC, deadalnix requested changes

2020-10-01 08:41 UTC, deadalnix commented on v2/src/layout/footer.js
> +          <a className={S.socialIcon} href="https://t.me/BCHUpdates">
https://t.me/bitcoincashfork might be best.

2020-10-01 08:41 UTC, deadalnix commented on v2/src/layout/nav-items.js
> +    text: "Services",
You just busted all the translations. How is that even remotely in the real of what get submitted for reviews?

2020-10-01 13:30 UTC, johnkuney commented on v2/src/layout/nav-items.js
> +    text: "Services",
Did you see my comment above? I addressed this and asked if you had any ideas. The fbt is breaking the build when applied within that component. I'm not sure why, but will continue to troubleshoot

2020-10-02 14:44 UTC, deadalnix requested changes

2020-10-02 14:44 UTC, deadalnix commented on v2/src/layout/nav-items.js
> +    text: "Services",
Because it is at top level and is therefore computed before the locale is setup. You need to wrap these thing into functions.

2020-10-03 02:51 UTC, johnkuney commented on v2/src/layout/nav-items.js
> +    text: "Services",
Okay thanks for that tip think I got it

2020-10-09 15:57 UTC, merged